version: "3"
services:
  web1:
    image: php:7.2-apache
    ports:
      - 8080:80
    volumes:
      - ./web1:/var/www/html:cached
  web2:
    image: php:7.2-apache
    ports:
      - 8081:80
    volumes:
      - ./web2:/var/www/html:cached
